spring:
  security:
    oauth2:
      client:
        registration:
          cat-client:
            client-id: cat-client
            client-secret: 7bf9882e-452f-4d26-985e-d940c028f35c
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/cat-client"
            scope: profile
        provider:
          cat-client:
            authorization-uri: http://host.docker.internal:11001/auth/realms/master/protocol/openid-connect/auth
            token-uri: http://host.docker.internal:11001/auth/realms/master/protocol/openid-connect/token
            user-info-uri: http://host.docker.internal:11001/auth/realms/master/protocol/openid-connect/userinfo
            user-name-attribute: preferred_username
cat-server:
  url: http://cat-server:8080/cat-server