name: Build
on:
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Build Image
        run: ./gradlew bootBuildImage --imageName=aaronyunan/cat-client:${{github.run_number}}

      - name: Docker Login
        uses: docker/login-action@v1.8.0
        with:
          username: ${{secrets.DOCKER_HUB_USERNAME}}
          password: ${{secrets.DOCKER_HUB_ACCESS_TOKEN}}

      - name: Push Image
        run: docker push aaronyunan/cat-client:${{github.run_number}}

      - name: Build helm values file
      - run: ./auto/generate-helm-values-file.sh ${{github.run_number}}

      - name: Release
      - uses: seanmiddleditch/gha-publish-to-git@master
        with:
          repository: https://github.com/milkchocolate/cat-home
          branch: master
          github_token: '${{ secrets.GITHUB_TOKEN  }}'
#          github_pat: '${{ secrets.GH_PAT }}'
          source_folder: helm/values.yaml
          target_folder: cat-client/values.yaml
          commit_author: GitOps Robot
        if: success() && github.event == 'push'